import "@styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@components/Nav";
import Provider from "@components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Nav />
          <div className="app">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
